#!/bin/bash
sudo apt update && sudo apt-add-repository universe && sudo apt dist-upgrade -y  && sudo ubuntu-drivers autoinstall && sudo apt update && sudo apt install gnome-tweaks cmatrix neofetch htop default-jdk telegram-desktop chrome-gnome-shell curl git   -y



